#!/bin/bash

#Author: chisj
#Time: 2015.7.22
#Describe: Create Database

#The username of mysql database
USER="root"

#The password of mysql database
PASS="ggflying"

#The datebase name will be created
DATABASE="Wordpress"

mysql -u $USER -p$PASS << EOF >/dev/null

CREATE DATABASE $DATABASE

EOF
gunzip < Wordpress20151121-10.sql.gz.sql.gz | /usr/local/mysql/bin/mysql -u root -p  Wordpress
